version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      caddy-image:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/katbin"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      katbin-image:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/singbox"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      singbox-image:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
