
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/somehow22/caddy:${VERSION:-latest}
    container_name: caddy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    dns:
      - 8.8.8.8
      - 208.67.222.222
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  caddy_data:
  caddy_config: