
services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/somehow22/caddy:${VERSION:-latest}
    container_name: caddy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    sysctls:
      net.core.rmem_max: 2500000
      net.core.wmem_max: 2500000
    dns:
      - 8.8.8.8
      - 208.67.222.222
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- https://localhost/health --no-check-certificate >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  caddy_data:
  caddy_config:
