services:
  singbox:
    image: ghcr.io/somehow22/singbox:latest
    container_name: singbox
    restart: unless-stopped
    volumes:
      - ./singbox-config:/etc/sing-box
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    network_mode: host
    environment:
      - LOAD_KERNEL_MODULE=false
    command: run -C /etc/sing-box
