name: Build and Push Caddy Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'caddy/**'
      - '.github/workflows/caddy-build-push.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'caddy/**'
      - '.github/workflows/caddy-build-push.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get Caddy version
      id: caddy_version
      run: |
        CADDY_VERSION=$(docker run --rm caddy:2-alpine caddy version | cut -d ' ' -f 1)
        echo "version=${CADDY_VERSION#v}" >> $GITHUB_OUTPUT
        echo "CADDY_VERSION=${CADDY_VERSION#v}" >> $GITHUB_ENV
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./caddy
        file: ./caddy/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        provenance: false
        outputs: type=registry,push=true
        tags: |
          ghcr.io/${{ github.repository_owner }}/caddy:latest
          ghcr.io/${{ github.repository_owner }}/caddy:2
          ghcr.io/${{ github.repository_owner }}/caddy:${{ env.CADDY_VERSION }}