name: Build and Push Caddy Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'caddy/**'
      - '.github/workflows/caddy-build-push.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'caddy/**'
      - '.github/workflows/caddy-build-push.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Read Caddy version from Dockerfile
      id: caddy_version
      run: |
        CADDY_VERSION=$(grep -E '^ARG CADDY_VERSION=' caddy/Dockerfile | head -1 | cut -d '=' -f2)
        echo "version=${CADDY_VERSION}" >> $GITHUB_OUTPUT
        echo "CADDY_VERSION=${CADDY_VERSION}" >> $GITHUB_ENV

    - name: Derive major tag
      run: |
        echo "CADDY_MAJOR=${CADDY_VERSION%%.*}" >> $GITHUB_ENV
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./caddy
        file: ./caddy/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        provenance: false
        build-args: |
          CADDY_VERSION=${{ env.CADDY_VERSION }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/caddy:latest
          ghcr.io/${{ github.repository_owner }}/caddy:${{ env.CADDY_MAJOR }}
          ghcr.io/${{ github.repository_owner }}/caddy:${{ env.CADDY_VERSION }}
