name: Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'deepnote/**'
      - '.github/workflows/deepnote-build.yml'
  workflow_dispatch:  # Allow manual triggering

env:
  IMAGE_NAME: deepnote-mpdev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./deepnote
          file: ./deepnote/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/deepnote-mpdev:latest
          