name: Build and Push Deepnote Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'deepnote/**'
      - '.github/workflows/deepnote-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [data, llm]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./deepnote
          file: ./deepnote/${{ matrix.image }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/deepnote:${{ matrix.image }}
          build-args: |
            IMAGE=${{ matrix.image }}
          labels: |
            org.opencontainers.image.authors="Magpie Labs"
            org.opencontainers.image.description="for deepnote dev"