name: Build and Push Katbin Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'katbin/**'
      - '.github/workflows/katbin-build-push.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'katbin/**'
      - '.github/workflows/katbin-build-push.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./katbin
        file: ./katbin/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/katbin:latest
          ghcr.io/${{ github.repository_owner }}/katbin:${{ github.sha }}
